######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 15 20:17:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += process.h
SOURCES += main.cpp process.cpp
