######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 14 15:52:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += process.h \
    MyDialog.h
SOURCES += main.cpp \
    MyDialog.cpp
