######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 15 20:16:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp MyDialog.cpp
